#!/bin/bash

QTVERSION=5.13.1

function dobuild {
    pushd PathGenCommon
    make CONFIG=release clean
    make CONFIG=release
    popd

    pushd XeroGenV1
    make CONFIG=release clean
    make CONFIG=release
    popd

    pushd PathFinderV1Gen
    make CONFIG=release clean
    make CONFIG=release
    popd

    pushd PoofsGenerator
    make CONFIG=release clean
    make CONFIG=release
    popd

    pushd XeroPathGenerator
    qmake -makefile
    make clean
    make
    popd

    qhelpgenerator html/xeropath.qhp -o html/xeropath.qch
    qhelpgenerator html/xeropath.qhcp -o html/xeropath.qhc
}

function docopy
{
    rm -rf xeropathgen

    mkdir -p xeropathgen
    mkdir -p xeropathgen/
    mkdir -p xeropathgen/generators
    mkdir -p xeropathgen/images
    mkdir -p xeropathgen/fields
    
    cp x64/release/XeroPathGenerator xeropathgen
    cp XeroPathGenerator/images/*.png xeropathgen/images
    cp fields/* xeropathgen/fields
    cp generators/*.json xeropathgen/generators
    cp PathFinderV1Gen/release/PathFinderV1Gen xeropathgen/generators
    cp XeroGenV1/release/XeroGenV1 xeropathgen/generators
    cp PoofsGenerator/release/PoofsGenerator xeropathgen/generators
    
    cp html/xeropath.qch xeropathgen
    cp html/xeropath.qhc xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/bin/assistant xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libQt5Charts.so.5 xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libQt5PrintSupport.so.5 xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libQt5Widgets.so.5 xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libQt5Gui.so.5 xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libQt5Network.so.5 xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libQt5Core.so.5 xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libQt5Core.so.5 xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libQt5Help.so.5 xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libicui18n.so.56 xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libicuuc.so.56 xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libicudata.so.56 xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libQt5Sql.so.5 xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libQt5XcbQpa.so.5 xeropathgen
    cp ~/Qt/$QTVERSION/gcc_64/lib/libQt5DBus.so.5 xeropathgen

    mkdir xeropathgen/imageformats
    cp ~/Qt/$QTVERSION/gcc_64/plugins/imageformats/libqgif.so xeropathgen/imageformats
    cp ~/Qt/$QTVERSION/gcc_64/plugins/imageformats/libqicns.so xeropathgen/imageformats
    cp ~/Qt/$QTVERSION/gcc_64/plugins/imageformats/libqico.so xeropathgen/imageformats
    cp ~/Qt/$QTVERSION/gcc_64/plugins/imageformats/libqjpeg.so xeropathgen/imageformats
    cp ~/Qt/$QTVERSION/gcc_64/plugins/imageformats/libqsvg.so xeropathgen/imageformats
    cp ~/Qt/$QTVERSION/gcc_64/plugins/imageformats/libqtga.so xeropathgen/imageformats
    cp ~/Qt/$QTVERSION/gcc_64/plugins/imageformats/libqtiff.so xeropathgen/imageformats
    cp ~/Qt/$QTVERSION/gcc_64/plugins/imageformats/libqwbmp.so xeropathgen/imageformats
    cp ~/Qt/$QTVERSION/gcc_64/plugins/imageformats/libqwebp.so xeropathgen/imageformats


    mkdir xeropathgen/platforms
    cp ~/Qt/$QTVERSION/gcc_64/plugins/platforms/libqxcb.so xeropathgen/platforms

    
    cp xeropath xeropathgen
    cp README.linux xeropathgen/README
}

dobuild
docopy

tar cvf xeropath.tar xeropathgen
rm -f xeropath.tar.bz2
bzip2 xeropath.tar
