#!/bin/bash

pushd PathGenCommon
make
popd

pushd XeroPathGenerator
qmake -makefile
make
popd

pushd XeroGenV1
make
popd

pushd PathFinderV1Gen
make
popd

mkdir -p xeropathgen
mkdir -p xeropathgen/bin
mkdir -p xeropathgen/fields
mkdir -p xeropathgen/generators
cp XeroPathGenerator/debug/XeroPathGenerator xeropathgen/bin
cp XeroPathGenerator/*.png xeropathgen/bin
cp guide/XeroPathGenerator.pdf xeropathgen/bin
cp fields/* xeropathgen/fields
cp generators/*.json xeropathgen/generators
cp PathFinderV1Gen/PathFinderV1Gen xeropathgen/generators
cp XeroGenV1/XeroGenV1 xeropathgen/generators

cp ~/Qt/5.13.0/gcc_64/lib/libQt5Widgets.so.5.13.0 xeropathgen/bin
cp ~/Qt/5.13.0/gcc_64/lib/libQt5Core.so.5.13.0 xeropathgen/bin
cp ~/Qt/5.13.0/gcc_64/lib/libQt5Charts.so.5.13.0 xeropathgen/bin
cp ~/Qt/5.13.0/gcc_64/lib/libQt5Gui.so.5.13.0 xeropathgen/bin
cp ~/Qt/5.13.0/gcc_64/lib/libQt5Svg.so.5.13.0 xeropathgen/bin

pushd xeropathgen/bin
ln -s libQt5Widgets.so.5.13.0 libQt5Widgets.so.5.13
ln -s libQt5Widgets.so.5.13.0 libQt5Widgets.so.5
ln -s libQt5Widgets.so.5.13.0 libQt5Widgets.so

ln -s libQt5Core.so.5.13.0 libQt5Core.so.5.13
ln -s libQt5Core.so.5.13.0 libQt5Core.so.5
ln -s libQt5Core.so.5.13.0 libQt5Core.so

ln -s libQt5Charts.so.5.13.0 libQt5Charts.so.5.13
ln -s libQt5Charts.so.5.13.0 libQt5Charts.so.5
ln -s libQt5Charts.so.5.13.0 libQt5Charts.so

ln -s libQt5Gui.so.5.13.0 libQt5Gui.so.5.13
ln -s libQt5Gui.so.5.13.0 libQt5Gui.so.5
ln -s libQt5Gui.so.5.13.0 libQt5Gui.so

ln -s libQt5Svg.so.5.13.0 libQt5Svg.so.5.13
ln -s libQt5Svg.so.5.13.0 libQt5Svg.so.5
ln -s libQt5Svg.so.5.13.0 libQt5Svg.so

popd

tar cvf xeropath.tar xeropathgen
