#!/bin/bash

QTVERSION=5.13.1

function dobuild {
    cd PathGenCommon
    make CONFIG=release clean
    make CONFIG=release
    cd ..

    cd XeroGenV1
    make CONFIG=release clean
    make CONFIG=release
    cd ..

    cd PathFinderV1Gen
    make CONFIG=release clean
    make CONFIG=release
    cd ..

    pushd PoofsGenerator
    make CONFIG=release clean
    make CONFIG=release
    popd

    qhelpgenerator html/xeropath.qhp -o html/xeropath.qch
    qhelpgenerator html/xeropath.qhcp -o html/xeropath.qhc

    pushd XeroPathGenerator
    qmake -makefile
    make clean
    make
    popd

}

function docopy {
    cp ~/Qt/$QTVERSION/clang_64/bin/Assistant.app/Contents/MacOS/Assistant x64/release/XeroPathGenerator.app/Contents/MacOS/Assistant
}

rm -rf x64/release
dobuild
docopy
ASSLOC=`pwd`/x64/release/XeroPathGenerators.app/Contents/MacOS/Assistant
macdeployqt x64/release/XeroPathGenerator.app -verbose=3 -always-overwrite -appstore-compliant -dmg -executable=$ASSLOC
cp x64/release/XeroPathGenerator.dmg .


